version: '2'

services:

  nodejs:
    image: nodejs
    container_name: nodejs
    build:
      context: .
      dockerfile: Dockerfile
    
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
        
        #  jenkins:
        #    image: istresearch/jenkins:latest
        #    ports:
        #      - '9090:8080'
        #      - '443:8443'
        #      - '50000:50000'
        #    volumes:
        #      - /data/jenkins:/var/jenkins_home
        #      - /var/run/docker.sock:/var/run/docker.sock

