version: '2'

services:

  nodejs:
    image: nodejs
    container_name: nodejs
    build:
      context: .
      dockerfile: Dockerfile
    
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
